// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjtXAxMpfptqqj0Jji1dq-8Amrqpoobn8',
    appId: '1:696163455879:web:d271423c00c22cfbae3922',
    messagingSenderId: '696163455879',
    projectId: 'moon-spotify',
    authDomain: 'moon-spotify.firebaseapp.com',
    storageBucket: 'moon-spotify.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvM3KPHC9aAVCicl5rS4cr37x5Ii0VHmY',
    appId: '1:696163455879:android:1ac28be705adcacaae3922',
    messagingSenderId: '696163455879',
    projectId: 'moon-spotify',
    storageBucket: 'moon-spotify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1LurSMslFnn4MO8EkIRo9Lyr__jB9zcw',
    appId: '1:696163455879:ios:0ff86c98e9d2d0c2ae3922',
    messagingSenderId: '696163455879',
    projectId: 'moon-spotify',
    storageBucket: 'moon-spotify.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1LurSMslFnn4MO8EkIRo9Lyr__jB9zcw',
    appId: '1:696163455879:ios:0ff86c98e9d2d0c2ae3922',
    messagingSenderId: '696163455879',
    projectId: 'moon-spotify',
    storageBucket: 'moon-spotify.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjtXAxMpfptqqj0Jji1dq-8Amrqpoobn8',
    appId: '1:696163455879:web:8340942b7c417776ae3922',
    messagingSenderId: '696163455879',
    projectId: 'moon-spotify',
    authDomain: 'moon-spotify.firebaseapp.com',
    storageBucket: 'moon-spotify.appspot.com',
  );
}
